{{- $fullName    := include "postgres.fullname" . -}}
{{- $configName  := default $fullName .Values.existingConfigMap -}}
{{- $secretName  := default $fullName .Values.existingSecret -}}
---
apiVersion:                      apps/v1
kind:                            StatefulSet
metadata:
  name:                          {{ $fullName }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  serviceName:                   postgres
  replicas:                      {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name:                  {{ .Chart.Name }}
          image:                 {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy:       {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name:            {{ $secretName }}
            - configMapRef:
                name:            {{ $configName }}
          ports:
            - containerPort:     5432
              name:              postgres
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name:              pgdata
              mountPath:         /var/lib/postgresql
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready
                - --dbname=$POSTGRES_DB
                - --username=$POSTGRES_USER
            initialDelaySeconds: 15
            timeoutSeconds:      5
            failureThreshold:    3
            periodSeconds:       10
            successThreshold:    1
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready
                - --dbname=$POSTGRES_DB
                - --username=$POSTGRES_USER
            initialDelaySeconds: 45
            timeoutSeconds:      5
            failureThreshold:    3
            periodSeconds:       10
            successThreshold:    1
      initContainers:
        - name:                  init
          image:                 busybox
          volumeMounts:
            - mountPath:         /var/lib/postgresql
              name:              pgdata
              subPath:           data
          command:
            - /bin/sh
            - -c
            - chown -R 70:70 /var/lib/postgresql
      volumes:
        - name:                  pgdata
          persistentVolumeClaim:
            claimName:           pgdata
  volumeClaimTemplates:

    - metadata:
        name:                    pgdata
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName:        gp2 # gp2 hostpath
        resources:
          requests:
            storage:             512Mi
