nameOverride: ""
fullnameOverride: ""
replicaCount: 1

image:
  repository: redis
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 6379

resources:
   requests:
     cpu: 100m
     memory: 128Mi

